### ISSUE TITLE
SEO 1.8.18 로 업데이트 후에 "Analytics"와 "기타" 설정들이 화면에 나타나지 않습니다.

### ISSUE THREAD

**Issue by paulryu03** [xpressengine/xe-module-seo#24]
제목 대로 SEO 1.8.0 에서 1.8.18 로 업데이트 후에 "Analytics"와 "기타" 설정들이 화면에 나타나지 않고 저장 버튼만 보입니다. 확인 부탁드립니다. 감사합니다.

**Comment by bnu** [comment]
아래와 같은 증상이라면.. '기능 활성화'에 체크하시면 설정 폼이 나타납니다.
혹, '기능 활성화' 체크박스 마저 보이지 않는다면 브라우저 cache 삭제 및 SEO 모듈을 다시 업로드한 후 확인해주세요.


<img width="498" alt="2016-03-09 10 41 18" src="https://cloud.githubusercontent.com/assets/53764/13622654/857495f6-e5e3-11e5-9c66-ed2b85225fa8.png">

**Comment by paulryu03** [comment]
안녕하세요 bnu님. 먼저 좋은 모듈 만들어 주셔서 감사합니다. ^^ 저의 경우에는 이미 검색엔진 최적화 기능 사용에 체크 되어 있는 경우구요. 기본 설정을 변경 및 저장은 이상이 없는데, Analytics 나 기타를 클릭하면 위와 같이 아무 것도 안나타나고 저장 버튼만 보이는 상태입니다. 저만의 문제인가 했는데, XETown 에서 다른 분들도 이와 같은 현상이 있다고들 하네요.

**Comment by paulryu03** [comment]
혹시나 해서 위에서 bnu 님께서 말씀해주신 대로 모듈 재업로드와 브라우저 캐시 및 관리자 화면에서의 캐시 재생성을 다 해봤는데도 같은 증상이 나타납니다. 그런데 참고로 이전 1.8.0 에서는 이런 문제가 없었습니다.

**Comment by bnu** [comment]
아아, 문제 확인했습니다.

**Comment by sejin7940** [comment]
tpl/AdminSetting.html  파일에서

161번째줄부터 나오는..
if(!$('#enable').is(':checked'))
{
	config.hide();
}

부분을 통째로 삭제하거나 주석처리하면 됩니다.
